### ISSUE TITLE
How to change html img src path

### ISSUE THREAD

**Issue by DanielYKPan** [AngularClass/angular-starter#1379]
Hi, guys,

I am sorry I don't follow the guidelines for contributing to this repository. But I have a question about how to change the html img tag src path.
Ex:
I have a dummy.component.html. This is an angular component html.
And I have a img tag inside it  
`<img  src="assets/img/photo.png">`

When I run the **npm run build:prod**, the html will be inserted into the main.[hash].bundle.js.
the img tag src path still the same as it in dummy.component.html.

How could I make it like `<img src="mypublicpath/assets/img/photo.png"> `when I run the **npm run build:prod** command?

I try to look at the webpack html-loader, but I could find any good example.
Can you guys give me some advices?
Thanks!!!

**Comment by jgornick** [comment]
For the time being, I'm using html-loader to handle any images inside my HTML templates.

Because we're copying the assets into dist, I would much rather have my HTML paths resolve properly. Also, respecting the `publicPath` output value.

**Comment by DanielYKPan** [comment]
@jgornick 
Yes, I tried to look at the html-loader. Could you please tell me how to configure the html-loader so that it works on my example?

**Comment by jgornick** [comment]
@DanielYKPan I just simply used the html-loader instead of the raw-loader.

I started to look at https://github.com/TheLarkInn/angular2-template-loader. However, I'm not sure if that's right. There's got to be an easier way to rewrite the paths.

@d3viant0ne Can you provide any insight into this issue?

**Comment by jgornick** [comment]
@DanielYKPan I've found a solution that worked for me:

``` javascript
/* HTML loader support for *.html
 * Returns file content as string. 
 * Used for requiring images via img:src.
 *
 * See: https://github.com/webpack/html-loader
 */
{
  test: /\.html$/,
  use: ['html-loader'],
  exclude: [ helpers.root('src', 'index.html') ]
},

/*
 * File loader for supporting images, for example, in CSS/HTML files.
 */
{
  test: /\.(jpg|png|gif)$/,
  use: [
    {
      loader: 'file-loader',
      query: {
        name: '/assets/img/[name].[ext]'
      }
    }
  ]
},
```

That configuration will run any required HTML files through the `html-loader` (see `angular2-template-loader`). The `html-loader` requires any paths specified in `img:src` (i.e. images). Because the images are now being required into the dependency graph, we use the `file-loader` for any required `jpg|png|gif` images and write their path to `/assets/img/[name].[ext]`. Now the URLs in the HTML templates have the correct path to the image assets specified in `img:src` (e.g. `{output.publicPath}/assets/img/[name].[ext]`). 

This also plays nicely with the `CopyWebpackPlugin` found in the `webpack.common.js` configuration.

@d3viant0ne Is it worth submitting a pull request to run the HTML templates through the `html-loader`?

**Comment by DanielYKPan** [comment]
@jgornick
I tried your solution on the clean latest angular2-webpack-starter project. It didn't work. I put your solution in webpack.prod.js, and specified the output.publicPath. The image assests still pointed to **/assets/img/[name].[ext]**, not **{output.publicPath}/assets/img/[name].[ext]**. 

Where did you put your solution to? And how you configure your project when this solution worked for you?

**Comment by jgornick** [comment]
@DanielYKPan Interesting. I am running the latest versions of all packages in my setup. So that might be one of the areas you'll want to check.

I did also move my metadata out into it's own file as described @ https://github.com/AngularClass/angular2-webpack-starter/compare/master...s2ugimot:improve-webpack-config-metadata-handling
