### ISSUE TITLE
Cannot build project due to error in hammerjs/index.d.ts

### ISSUE THREAD

**Issue by aeisenberg** [AngularClass/angular-starter#1417]
* **I'm submitting a bug report**

* **What is the current behavior?**

Steps to reproduce:

* clone repository, current `origin/master` is c597344
* `npm install`
* `npm run build:prod`
* build fails with following error message:

```
[at-loader] Checking started in a separate process...

[at-loader] Checking finished with 1067 errors
Error in bail mode: [at-loader] node_modules/@types/hammerjs/index.d.ts:9:5
    Duplicate identifier 'export='.

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/andrew.eisenberg/.nvm/versions/node/v7.4.0/bin/node" "/Users/andrew.eisenberg/.nvm/versions/node/v7.4.0/bin/npm" "run" "build:prod"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack-starter@5.1.1 build:prod: `npm run clean:dist && webpack --config config/webpack.prod.js  --progress --profile --bail`
npm ERR! Exit status 1
```

Also attaching the full npm-debug.log.
[npm-debug.log.txt](https://github.com/AngularClass/angular2-webpack-starter/files/729834/npm-debug.log.txt)

* **What is the expected behavior?**

Project build successfully.

* **Please tell us about your environment:**

- node 7.4
- npm 4.05
- Angular version: 2.4.3
- Browser: N/A
- macos

**Comment by aeisenberg** [comment]
I also checked out tag **v5.2.0** and had the same behavior.

**Comment by aeisenberg** [comment]
**Update:**

By making the following change, the build passes:

```
$ git diff
diff --git a/tsconfig.webpack.json b/tsconfig.webpack.json
index 994c56f..cc92e65 100644
--- a/tsconfig.webpack.json
+++ b/tsconfig.webpack.json
@@ -26,7 +26,8 @@
     "node_modules",
     "dist",
     "src/**/*.spec.ts",
-    "src/**/*.e2e.ts"
+    "src/**/*.e2e.ts",
+    "typings"
   ],
```

**Comment by leonardlin** [comment]
I have the same error.
It builds fine on my development machine but it fails on the CI server.

The error on the CI server:

`[at-loader] Checking started in a separate process...

[at-loader] Checking finished with 132 errors
Error in bail mode: [at-loader] node_modules/@types/hammerjs/index.d.ts:9:5
    TS2300: Duplicate identifier 'export='.

npm ERR! Linux 3.10.0-514.6.1.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:prod"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack-starter@5.4.1 build:prod: `npm run clean:dist && webpack --config config/webpack.prod.js  --progress --profile --bail`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-webpack-starter@5.4.1 build:prod script 'npm run clean:dist && webpack --config config/webpack.prod.js  --progress --profile --bail'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-webpack-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean:dist && webpack --config config/webpack.prod.js  --progress --profile --bail
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-webpack-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-webpack-starter
npm ERR! There is likely additional logging output above.
`

I tried @aeisenberg hack with "typings" didn't work for me. It caused another error.
`   [0] ./src/main.browser.ts 420 bytes {0} [built] [failed] [1 error]
        factory:214ms building:2135ms = 2349ms
   [1] ./src/polyfills.browser.ts 420 bytes {1} [built] [failed] [1 error]
        factory:92ms building:2218ms = 2310ms

ERROR in ./src/polyfills.browser.ts
Module build failed: Error: parseQuery should get a string as first argument
    at Object.parseQuery (/var/lib/jenkins/workspace/prod-ofbiz/ofbiz/hot-deploy/freshmarket/frontend/partner/node_modules/loader-utils/index.js:68:9)
    at Object.Angular2HMRLoader (/var/lib/jenkins/workspace/prod-ofbiz/ofbiz/hot-deploy/freshmarket/frontend/partner/node_modules/@angularclass/hmr-loader/index.js:10:21)

ERROR in ./src/main.browser.ts
Module build failed: Error: parseQuery should get a string as first argument
    at Object.parseQuery (/var/lib/jenkins/workspace/prod-ofbiz/ofbiz/hot-deploy/freshmarket/frontend/partner/node_modules/loader-utils/index.js:68:9)
    at Object.Angular2HMRLoader (/var/lib/jenkins/workspace/prod-ofbiz/ofbiz/hot-deploy/freshmarket/frontend/partner/node_modules/@angularclass/hmr-loader/index.js:10:21)
Child html-webpack-plugin for "index.html":
`

I think it has to do with the environment / version since it's working on my local dev.

**Comment by leonardlin** [comment]
I had the same problem on the CI server.

I cleaned out the directory, made a fresh checkout and it worked.
perhaps that helps you too
