### ISSUE TITLE
cannot read property 'probe' of undefined

### ISSUE THREAD

**Issue by Shiroh1ge** [AngularClass/angular-starter#1573]
* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
Hello, I have just updated to Angular 4 RC1 and Typescript 2.2 and have been getting a weird error and some unresolved variables. I'm getting a `cannot read property 'probe' of undefined` in the console, which I think is coming from this piece of code: 
```
  _decorateModuleRef = (modRef: any) => {
    const appRef = modRef.injector.get(ApplicationRef);
    const cmpRef = appRef.components[0];

    let _ng = (<any> window).ng;
    enableDebugTools(cmpRef);
    (<any> window).ng.probe = _ng.probe;
    (<any> window).ng.coreTokens = _ng.coreTokens;
    return modRef;
  };
```
Also my IDE is complaining a lot about unresolved variables, do you have any idea why is this happening? Should I revert to a previous version? 

- Angular version: 4.0.0-rc.1

**Comment by kemalcany** [comment]
If you move 

`enableDebugTools(cmpRef);`

above 

`let _ng = (<any> window).ng;`

you can bypass the error, but the probe and coreTokens wouldn't have been set properly which will disable some  debugging functions such as Augury.

It happens because window doesnt come with a ng property after the 4.rc.1 update... But I couldn't come up with a fix at this time unfortunately...

**Comment by Shiroh1ge** [comment]
@kemalcany it appears to be fixed: https://github.com/angular/angular/issues/14738, probably in the next update or so, will use that as a temporary solution, thanks!
