### ISSUE TITLE
Cannot load lazy module if we assign a variable to routerConfig loadChildren 

### ISSUE THREAD

**Issue by vasanthdharmu** [AngularClass/angular-starter#1631]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
Getting an error below.

**Working Fine:**

routerConfig.unshift({
			path: 'detail',
			loadChildren: './+detail#DetailModule'
})

**Not working:**

let xxx = "./+detail#DetailModule";
routerConfig.unshift({
			path: 'detail',
			loadChildren: xxx 
})

Throwing the error below.

EXCEPTION: Uncaught (in promise): Error: Cannot find module './+detail'.
Error: Cannot find module './+detail'.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

loadChildren should accept the variable and lazy module should work.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by jbeckton** [comment]
This is most likely an issue with ng-router-loader, my guess is that it will not work since that loader looks at the router module file as a string so that it can find and replace the loadChildren property with  webpack friendly code. 

[if you look at this code](https://github.com/shlomiassaf/ng-router-loader/blob/master/src/builtin_codegens.ts) you can see what the loader replaces your config with so it works with webpack. i guess if you use this code snippet instead of the loader you can make it work as desired.

 `loadChildren: function() { return new Promise(function (resolve) {`,
    `  require.ensure([], function (require) {`,
    `    resolve(${requireString});`,
    `  }${webpackChunkName});`,
    `})}`


see docs here https://github.com/shlomiassaf/ng-router-loader
