### ISSUE TITLE
Integration with Ionic2

### ISSUE THREAD

**Issue by DanielKucal** [AngularClass/angular-starter#1650]
Hi, has anyone here successfully integrated `angular2-webpack-starter` with Ionic2? It would be great to have a how-to (wiki is missing it), or even better a branch in this repository. I'm currently facing the challenge, so any tips are welcome too! Thanks.

**Comment by almothafar** [comment]
Simple answer, I don't think there is any chance to make it with ionic, as for example, no UI route, also ionic got their scripts, structure and many low quality code to handle.

I was working in Ionic2 project I got to refactor ionic2 project to this webpack.

**Comment by DanielKucal** [comment]
@almothafar, thanks for your participation. I know the code will need changes in some places, but I think the hardest part to integrate is compilation and project structure (which I wouldn't want to change btw). Did you abandon mobile applications or use something else for that?

**Comment by almothafar** [comment]
@DanielKucal we were think about single application for web and mobile, but because of issues and bugs and waste of time, we decide to give up on Ionic2, and make a website and 2 native app, would save time more than dealing with Ionic2, actually I Ionic 1.3 is way better than ionic2 (in code and structure).

**Comment by DanielKucal** [comment]
Thanks for sharing your experience.
