### ISSUE TITLE
How do I switch this project to support universial

### ISSUE THREAD

**Issue by alanhg** [AngularClass/angular-starter#1723]
How to switch this project to support the universial, this project has this plan? I do not want to create a separate project to do universial, that is, the server rendering.

**Comment by SherlockStd** [comment]
you mean translation ?

**Comment by thinkingmedia** [comment]
@heqiang421 The feature was released with Angular 4, before then it was still in beta.

Angular Starter is not yet fully Angular 4 and there is another issue related to updating the project.

**Comment by colinskow** [comment]
You could probably copy and paste the important parts from this repo to add Angular Universal support:
https://github.com/robwormald/ng-universal-demo

If we are going to add Universal support to this starter, I would prefer to maintain it in a separate branch to avoid confusing new users with the added complexity.

**Comment by colinskow** [comment]
@thinkingmedia this repo is now 100% Angular 4.

**Comment by SherlockStd** [comment]
@thinkingmedia is Universial required for Google to crawl an Angular 4 app correctly ?

**Comment by thinkingmedia** [comment]
@SherlockStd yes, without Universial the web server will always send the `index.html` page **as is** without any Angular code running. Now, you'll find some articles online talking about how Google now runs JavaScript when crawling, but I've found this to be very limited. Appears Google is only doing this when they are *inspecting* a website to see if violates any of their rules. Otherwise, the HTML that is indexed for the search engine is HTML that hasn't been altered by JavaScript.

Keep in mind that you need to run NodeJS as your web server if you want to use Universial. Tomcat/Apache/Nginx will not work as your web server (as far as I know).

**Comment by SherlockStd** [comment]
ah yeah that's bad ... It will be nice if Univiersal will be able to generate statics files which the only purpose is to be crawled by bots :/

**Comment by thinkingmedia** [comment]
@SherlockStd you can if you want (or need). You just run a web crawler against your Universal URL and bake the HTML files to disk, and then use those files.

The problem with this approach is that the HTML is static. The main idea behind Angular is dynamic changing content. (i.e. this wouldn't be a good idea for a twitter style website).

**Comment by lubkoKuzenko** [comment]
what is the status of server side rendering support?

**Comment by SherlockStd** [comment]
@heqiang421 @lubkoKuzenko you can both take a look to https://scotch.io/tutorials/server-side-rendering-in-angular-2-with-angular-universal, and a pull request will be much appreciated if you run into this

**Comment by minhnguyenwp** [comment]
I'm still waiting for this feature in angular-starter , server rendering by A4 universal. i need to upgrade my existing system, it's angular-starter v6.0

**Comment by gomesNazareth** [comment]
@SherlockStd   I cannot use an nginx server to serve angular universal ?. I am currently using gzip with nginx server to serve my angular project and it will be problem to change to a node server. Is there any other alternative ?

**Comment by SherlockStd** [comment]
@gomesNazareth I see you commented on https://github.com/angular/universal-starter/issues/346, apparently he was using an open-source projet already working.
You serve compiled file through Nginx is that is ? I do the same so I think that such resource will be useful.

But unfortunately according to @scott-wyatt there is no way to do it without a NodeJS app and a nginx proxy, see https://github.com/angular/universal/issues/554#issuecomment-249622433.
Angular Universal being a node application, it can't by definition be pre-rendered. It's like trying to pre-render a full REST API.

The easiest solution seems to be:
1) Compile your files for production
2) Serve them directly with your nginx.
3) Run Universal with pm2.
4) Start with [this gist](https://gist.github.com/SherlockStd/46bae6394f5d379f13785ce63684a5a0#file-nginx-conf-L27) and derivate it to integrate a proxy for the node instance running Universal, targetting only bots.

**Comment by gomesNazareth** [comment]
@SherlockStd  Thanks for replying. This looks like a good solutions . Request from bots will go to a node server and other wise ngnix server.
Have you used angular universal with webpack ?

**Comment by SherlockStd** [comment]
@gomesNazareth Not yet sorry, i'm currently working on an opensource project for my studies and I present it to got my diploma so I'll see that once the project will be ready :)

**Comment by thinkingmedia** [comment]
The need to run your web server as NodeJS shouldn't come as a surprise. Universal has been in development since the start of Angular 2 and was always a NodeJS app. It was behind the decision to make the browser layer a replaceable module and why you should not use jQuery with Angular anymore or other browser dependent libraries.

Keep in mind that designing an Angular app that works with Universal is a completely different design approach then just a single-page app, and further more complicated if you're also building for mobile.

Just turning on Universal isn't enough in most cases. It takes time and will require changes to your app, because of the problems it introduces.

The best advise is to start with Universal from the very beginning, and expect there to be a lot of work to turn it on later.
