### ISSUE TITLE
npm start shows : loading...

### ISSUE THREAD

**Issue by dimitri-a** [AngularClass/angular-starter#1769]
* **Do you want to request a *feature* or report a *bug*?**
How can I run the angular-starter?

* **What is the current behavior?**
When I run npm start from the commandline I get: loading... in the browser?

* **Please tell us about your environment:**

osx mac sierra, node 7.9.0

**Comment by venkataraghu** [comment]
same issue on my system. windows 10, node v6.10.0

**Comment by dudemonkey** [comment]
same issue on my system. windows 10, node v6.10.0 . I suspect that the problem lies in the node version .
I found the version in package.json is 7.0.13 . I will try it at night

**Comment by supermarioim** [comment]
same here, tried fresh installation on node v7.10.0 and v6.9.1 (linux mint, ubuntu based). all deps are installed. no error in chrome console.

**Comment by dwsmiontmigachcanc** [comment]
I think the Readme.md needs to be updated.  The clone command says:
https://github.com/angularclass/angular2-webpack-starter.git

But the clone URL  and zip download point to:
https://github.com/AngularClass/angular-starter.git

The angular-starter.git runs fine: no loading and not error for regex.test.  

**Note** that I did upgrade to node 8.0.0 before pulling angular-starter so that may have helped.  But webpack.common.js is definitely different between the two: the angular-starter version has the PreloadWebpackPlugin code commented out but the angular2-webpack-starter does not.

**Comment by dimitri-a** [comment]
runs fine now. thanks

cheers,
Dimitri

On Thu, Jun 1, 2017 at 5:34 AM, dwsmiontmigachcanc <notifications@github.com

**Comment by supermarioim** [comment]
I just tried with node.js v8.0.0 and still nothing, just loading screen and no errors at all. it was installed using https://github.com/AngularClass/angular-starter.git URL. i have couple of older versions running and no problems at all, but this version can't pass further then loading screen.

**Comment by supermarioim** [comment]
pulled latest changes, it seams to be fixed

**Comment by gdi2290** [comment]
sorry about that. It was an issue with latest version of zone.js
https://github.com/angular/zone.js/issues/746
