### ISSUE TITLE
Run webpack server without running build?

### ISSUE THREAD

**Issue by erictraub** [AngularClass/angular-starter#1856]
Is there anyway to run the webpack server without building it for dev before hand?  I just want to run the server command but not sure how to do it.  (I would have wrote this on AngularClass slack but the link doesn't work).

**Comment by vadjs** [comment]
You **must** compile files like `.ts/.scss` to run server with angular application. It's needed because browser don't understand `.ts/.scss` file formats, it understands onlu `.js/.css`.

If you need to run dev server several times after single build you can do it through `npm run build:dev` to build and `npm run server prod` to run server.
