### ISSUE TITLE
How does the app still run if vendor.browser.ts was removed?

### ISSUE THREAD

**Issue by IAMtheIAM** [AngularClass/angular-starter#1860]
Just wondering, how is it possible that the app compiles and runs still even though all the @angular/core etc stuff from vendor.browser.ts no longer gets built by webpack, since that file is now missing? 

Was there a change to angular or webpack which makes those imports obsolete?

**Comment by shlomiassaf** [comment]
@IAMtheIAM It doesn't really have to be in `vendor.browser.ts` to be part of the webpack process.

The vendor file was the place to put all vendors that you want to have put in the vendors chunk (bundle).

Without it webpack will still load all the vendor files since they are referenced (import X from Y) inside modules, so each reference is a place for webpack to add that vendor to the bundle.

I think now this can be done without an vendor file, but with a "catch-all" chunk that will be used for that purpose - CommonsChunkPlugin

It was commented out 2+ months ago, don't know why.

**Comment by IAMtheIAM** [comment]
@shlomiassaf Thanks for the explanations. I thought the vendors files would be loaded from the `import X from Y` statements, glad you confirmed.
