### ISSUE TITLE
import bootstrap error

### ISSUE THREAD

**Issue by ycoe** [AngularClass/angular-starter#504]
when i add jquery and bootstrap follow [How to use Bootstrap 4 and Sass (and jQuery)](https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-use-Bootstrap-4-and-Sass-%28and-jQuery%29)

i got the error info:

ERROR in end of the stream or a document separator is expected at line 7, column 19:
      <head prefix="og: http://ogp.me/ns# fb: http://o ... 
                      ^
 @ ./~/bootstrap-loader/loader.js 1:0-44

**Comment by atulhm** [comment]
I'm getting the same error.  Did you find a solution?

**Comment by atulhm** [comment]
found the issue:  when saving .bootstraprc per the instructions, an html file is pulled instead of the contents.  

SOLUTION:  create the file manually and copy/paste the contents.  
I've attached the file here.  **Be sure to rename it to .bootstraprc**

[bootstraprc.txt](https://github.com/AngularClass/angular2-webpack-starter/files/235517/bootstraprc.txt)

**Comment by gdi2290** [comment]
sorry this may sound super rule but I'm closing long standing issues and refactoring the codebase. If you run into this problem again feel free to open another issue
