### ISSUE TITLE
Future of this project comparing to angular cli?

### ISSUE THREAD

**Issue by asadsahi** [AngularClass/angular-starter#968]
I have been loving this project, but there are few things which I am not clear at the moment:

1) Angular cli is evolving (still not as mature as it has to be), but will we be needing such starter projects. What is the roadmap comparing to cli based projects?

2) Not sure about the purpose of following packages. Are these packages tying us to a specific use case?
    ```
"@angularclass/conventions-loader": "^1.0.2",
    "@angularclass/hmr": "^1.0.1",
    "@angularclass/hmr-loader": "^1.0.1",
    "@angularclass/request-idle-callback": "^1.0.7",
    "@angularclass/webpack-toolkit": "^1.3.3",

```
```

**Comment by paralin** [comment]
Hot module reload (hmr) for developing faster (no full refresh every change). webpack-toolkit stuff I think was for async reload but we're not sure what the status of that is as of now.

**Comment by katallaxie** [comment]
@asadsahi 

(1) From my experience it is, that most projects are not boilerplate projects, but need a high-level of customization and proprietary solutions. That's when the Starter becomes handy. Because it also captures many of these, either in the code, or in the `README.ME`. 

(2) That is automatically transform Component Metadata to `require`statements, to Hot Module Reloading, and have async components. So, a lot of stuff that is hard to have in the CLI as you have to have a lot of boilerplate code.

**Comment by rubenCodeforges** [comment]
> (2) That is automatically transform Component Metadata to requirestatements, to Hot Module Reloading, and have async components. So, a lot of stuff that is hard to have in the CLI as you have to have a lot of boilerplate code.

ive removed this as it is not required for development, its just a tool and not a strict requirement.

**Comment by gdi2290** [comment]
ya I need to remove these packages until I update their useage 
"@angularclass/request-idle-callback": "^1.0.7",
"@angularclass/webpack-toolkit": "^1.3.3",
the starter's goal is to make the development workflow as easy as possible for production. I'm also working with the cli team and webpack. The angularclass starter repos will be one of the first repos to be used for a tool we made that we might show off a bit at AngularConnect

**Comment by asadsahi** [comment]
@gdi2290 is that tool a surprise? Are we expecting an announcement like Angular 2 Team does? :)

Really looking forward for DLL usage with webpack because one of [my project](https://github.com/asadsahi/AspNetCoreSpa) rebuilds in roughly 150-250 ms compared to angular2-webpack-starter takes roughly 1-1.5 seconds on same machine.

**Comment by fxck** [comment]
This repo will hopefully include DLL as well.. one day.

Things I would really like to see:

1. DLL(https://github.com/AngularClass/angular2-webpack-starter/issues/843#issuecomment-242577597)
2. integrated AOT commands (there are some efforts at this repo https://github.com/qdouble/angular2webpack2-starter)
3. tidying up of configs and the build system generally, now that it's using webpack2 and you can actually use es6 everywhere... CLI has got pretty nice webpack configs for example(https://github.com/AngularClass/angular2-webpack-starter/issues/910)

**Comment by rubenCodeforges** [comment]
@gdi2290 do you use windows ?

**Comment by gdi2290** [comment]
@rubenCodeforges  I don't use windows

**Comment by rubenCodeforges** [comment]
@asadsahi do you use windows ?

**Comment by asadsahi** [comment]
@rubenCodeforges yes I do, is everything ok??? :)

**Comment by rubenCodeforges** [comment]
@asadsahi just asking because youve mentioned dll , on unix we dont have them

**Comment by asadsahi** [comment]
@rubenCodeforges [dll ](http://webpack.github.io/docs/build-performance.html)is a concept in webpack too. This is to do with having more performance out of webpack.

**Comment by fxck** [comment]
@gdi2290 could you reply to this https://github.com/AngularClass/angular2-webpack-starter/issues/968#issuecomment-246180363 ? What's the current situation with this repo now that angular2 is out? Are you busy preparing for conferences or something? Could we do something to help coordinate effort of updating and tidying up this repo? I know it interests a lot of people. :)

Thank you.

cc @DzmitryShylovich

**Comment by fxck** [comment]
Hello? @katallaxie @gdi2290

**Comment by mikeumus** [comment]
### Considering becoming an Angular CLI template or using @ngtools/webpack

With the Angular CLI becoming so powerful and central to workflow, it's a good time to consider if this starter makes sense to work as an Angular CLI template. See "[App Creation Using Template](https://github.com/angular/angular-cli/wiki/Stories#app-creation-using-template)" in the CLI wiki. Becoming a template would look something like this for a user to get started:

`ng new my-ng2-app --template=angular2-webpack-starter`

Or adopting [`@ngtools/webpack`](https://www.npmjs.com/~ngtools) to not miss out on any of the innovations happening on the CLI like "code splitting" (see below) and other optimizations. 

See the benefits and ability to use `@ngtools/webpack` standalone from the Angular CLI as presented in [Stephen Fluin's Angular CLI talk](https://youtu.be/uBRK6cTr4Vk?t=6m45s) at Angular Connect 2016:

- Compiles SCSS/LESS
- TypeScript transpilation
- Bundles JavaScript, CSS
- Asset optimization
- Virtual filesystem for assets
 - For serving local assets and compile versions.
- Live-reload via websockets
- Code splitting
  - Recognizing the use of loadChildren in the router, and bundling those modules separately so that any dependencies of those modules are not going to be loaded as part of your main bundle. These separate bundles will be pulled out of the critical path of your application, making your total application bundle much smaller and loading it much more performant.

**Comment by gdi2290** [comment]
The next change to the repo would diverge from the current folder structure and the current style guide with the focus on production apps. The change would also include AoT,  DLL only for dev and SCSS (since it's the most popular one). Anything the CLI has will be included plus more depending on the opinions and style guide of @AngularClass. The only problem right now is finding the weekend to work on it or start training maintainers for future updates. The CLI and starter repos have different goals which is why this repo will always exist.

**Comment by admosity** [comment]
Any news on this front? I am using this in a large corporate setting and would be willing to maintain and backport some of my enhancements over. I have gone this route because of the blackbox nature of angular-cli being too risky. I have seen the intake of issues and PRs have slowed, for example: #1640, #1637 should have been merged already.

Some enhancements I currently have:

* Frontend app config
* Commitizen
* Standard changelog
![image](https://cloud.githubusercontent.com/assets/4655972/24457120/3e0ad752-1463-11e7-9214-37c2b58f1bd2.png)
* Separate IE polyfill and IE stylesheet bundle
![image](https://cloud.githubusercontent.com/assets/4655972/24457142/5698e07a-1463-11e7-842d-2834177243f9.png)
* Angular 4
* Custom `includePaths` setup with scss so components can consume a common import
Example: https://github.com/angular/angular-cli/pull/2747#issuecomment-268651574
* Postcss/autoprefixer
* Headless protractor and karma configuration via PhantomJS

**Comment by gdi2290** [comment]
updates will be in the same issue here https://github.com/AngularClass/angular-starter/issues/1686
